name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Code Quality ---
      

      - name: Check formatting with black
        run: black --check .

      - name: Static typing with mypy
        run: mypy app/ || true  # allow partial typing

      # --- Security Checks ---
      - name: Security scan with Bandit
        run: bandit -r app/ -x tests

      - name: Dependency vulnerability check with Safety
        run: safety check || true  # don't fail build yet

      # --- Tests ---
      - name: Run tests
        run: pytest tests/ --maxfail=1 --disable-warnings -q
